name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: deps
        run: "sudo apt-get update && sudo apt-get install just"
      - name: "build"
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: just clean default
      - name: "compress"
        run: "tar czvf git-tools-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz -C target/ ."
      - name: "hashes"
        run: "sha256sum *.tar.gz >> git-tools-${{ matrixo.goos }}-${{ matrix.goarch}}.sha256sum"
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            git-tools-*.tar.gz
            git-tools-*.sha256sum
